Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -202,6 +202,21 @@ jobs:
           ls -l /dev/kvm
           test -e /dev/kvm
 
+      - name: Get Debug Application ID
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          PACKAGE_NAME=$(./gradlew -q printDebugApplicationId)
+
+          if [[ -z "$PACKAGE_NAME" ]]; then
+            echo "ERROR: Application ID is empty."
+            exit 1
+          fi
+
+          echo "PACKAGE_NAME=$PACKAGE_NAME" >> "$GITHUB_ENV"
+          echo "Application ID: $PACKAGE_NAME"
+
       - name: Run Instrumented Tests for (${{ matrix.name }})
         uses: ReactiveCircus/android-emulator-runner@v2
         with:
@@ -214,10 +229,4 @@ jobs:
           emulator-options: -no-snapshot-save -no-window -gpu off -noaudio -no-boot-anim -camera-back none
           disable-animations: true
           script: |
-            bash -c '
-              set -e
-
-              PACKAGE_NAME=$(./gradlew -q printDebugApplicationId) 
-              echo "Using package name: $PACKAGE_NAME"
-      
-            '
+            ""
